import { createClient } from 'next-sanity';

/**
 * Seeds the first 3 /blog articles. Targets non-brand queries with real GSC
 * impressions but near-zero rank (positions 40-99), and the SXO finding that
 * every Marmo target query's SERP is dominated by comparison content while
 * the site had none. Idempotent (fixed _ids).
 *
 * Run: export $(grep -E '^(SANITY_WRITE_TOKEN|NEXT_PUBLIC_SANITY_PROJECT_ID|NEXT_PUBLIC_SANITY_DATASET)=' .env | xargs) \
 *        && npx tsx scripts/seed-blog-articles.ts
 */

const projectId = process.env.NEXT_PUBLIC_SANITY_PROJECT_ID;
const dataset = process.env.NEXT_PUBLIC_SANITY_DATASET || 'production';
const token = process.env.SANITY_WRITE_TOKEN;
if (!projectId) throw new Error('Missing NEXT_PUBLIC_SANITY_PROJECT_ID');
if (!token) throw new Error('Missing SANITY_WRITE_TOKEN');

const client = createClient({
	projectId,
	dataset,
	token,
	apiVersion: '2026-07-01',
	useCdn: false,
});

let k = 0;
const key = () => `k${k++}`;
type Seg = string | { t: string; href: string };

function rich(style: string, segments: Seg[]) {
	const markDefs: { _type: string; _key: string; href: string }[] = [];
	const children = segments.map(seg => {
		if (typeof seg === 'string') return { _type: 'span', _key: key(), text: seg, marks: [] as string[] };
		const mk = key();
		markDefs.push({ _type: 'link', _key: mk, href: seg.href });
		return { _type: 'span', _key: key(), text: seg.t, marks: [mk] };
	});
	return { _type: 'block', _key: key(), style, markDefs, children };
}
const p = (...s: Seg[]) => rich('normal', s);
const h2 = (t: string) => rich('h2', [t]);
function bullets(items: Seg[][]) {
	return items.map(segs => ({ ...rich('normal', segs), listItem: 'bullet', level: 1 }));
}

interface Article {
	id: string;
	slug: string;
	title: string;
	excerpt: string;
	seoTitle: string;
	seoDescription: string;
	body: unknown[];
}

const articles: Article[] = [
	{
		id: 'article-icon-button-marmo-vs-mui',
		slug: 'icon-button-marmo-ui-vs-mui',
		title: 'Icon Button: Marmo UI vs MUI',
		excerpt:
			'A side-by-side look at the Icon Button component in Marmo UI and MUI — API shape, accessibility defaults, and what changes when an AI agent is the one writing the code.',
		seoTitle: 'Icon Button Component: Marmo UI vs MUI (2026)',
		seoDescription:
			'Compare the Icon Button component in Marmo UI and MUI — props, accessibility defaults, sizing, and how each behaves when generated by an AI coding agent.',
		body: [
			p(
				'An icon-only button looks simple until you have to get the accessibility right: it needs a label a screen reader can announce, a focus ring, and a hit target that meets 44px on touch devices even if the icon itself is 16px. Here is how ',
				{ t: 'Marmo UI’s Icon Button', href: '/docs/components/icon-button' },
				" compares to MUI's.",
			),
			h2('API shape'),
			p(
				"MUI's IconButton wraps any child icon element and exposes size (small/medium/large), color, and edge props inherited from its broader Button family. It is flexible but the accessible label is opt-in — you pass aria-label yourself, and it is easy to ship an icon button with no accessible name if you forget.",
			),
			p(
				"Marmo UI's IconButton takes a required label prop that doubles as both the tooltip text and the aria-label, so there is no accessible-icon-button footgun by default. Icon is passed as a component reference, sizing follows Marmo's token scale (sm/md/lg) rather than free-form pixel values.",
			),
			h2('Accessibility defaults'),
			...bullets([
				['MUI: accessible name is opt-in via aria-label; nothing stops you from shipping unlabeled icon buttons.'],
				['Marmo UI: label is required at the type level, so an unlabeled icon button is a compile error, not a runtime accessibility bug.'],
				['Both meet 44px minimum hit target at default sizing; MUI requires you to verify this yourself at "small" size, Marmo enforces a minimum touch target regardless of visual icon size.'],
			]),
			h2('Why this matters more when an AI agent writes the code'),
			p(
				'A required label prop is a small API decision with an outsized effect once you are prompting an agent to "add a delete icon button" instead of writing it by hand. With MUI, an agent can generate a perfectly compiling, silently inaccessible button. With Marmo, the type system forces the label into existence before the code will build — one of the reasons Marmo’s MCP-connected component library exists at all: constraints that catch mistakes at generation time, not in a later audit.',
			),
			p(
				'See the full prop reference on the ',
				{ t: 'Icon Button docs page', href: '/docs/components/icon-button' },
				', or browse the rest of the ',
				{ t: 'component library', href: '/components' },
				'.',
			),
		],
	},
	{
		id: 'article-radio-group-marmo-vs-mui',
		slug: 'radio-group-marmo-ui-vs-mui',
		title: 'Radio Group: Marmo UI vs MUI',
		excerpt:
			'Comparing the Radio Group component in Marmo UI and MUI — composition model, keyboard navigation, and the Radio Card variant Marmo ships that MUI does not have built in.',
		seoTitle: 'Radio Group Component: Marmo UI vs MUI (2026)',
		seoDescription:
			'Marmo UI vs MUI Radio Group: composition API, keyboard navigation, and the card-style radio variant Marmo ships out of the box.',
		body: [
			p(
				'Radio groups look like a solved problem until you need arrow-key navigation between options, a fieldset-level error state, or a card-style selection UI instead of a bare circle input. Here is how ',
				{ t: 'Marmo UI’s Radio Group', href: '/docs/components/radio-group' },
				" compares to MUI's RadioGroup.",
			),
			h2('Composition model'),
			p(
				"MUI's RadioGroup is a controlled wrapper around individual FormControlLabel + Radio pairs — flexible, but you assemble the label, the input, and the layout yourself for every option, and value/onChange wiring is standard React controlled-component boilerplate.",
			),
			p(
				"Marmo UI's RadioGroup takes an items array (value, label, description) and renders the full set, including layout and keyboard navigation, from that one prop. There's also a separate RadioCard component for card-style selection (icon + title + description in a bordered, clickable card) — a pattern MUI doesn't ship a built-in equivalent for; you'd compose it yourself from Radio + Card.",
			),
			h2('Keyboard navigation'),
			...bullets([
				['Both correctly implement arrow-key navigation between options within a group per the native radio-input behavior.'],
				['MUI: error/helper text is wired through FormControl + FormHelperText, assembled per use.'],
				['Marmo UI: error and description text are built into the same items-array API, so the accessible description-to-input association (aria-describedby) is handled by the component, not left to the consumer to wire correctly.'],
			]),
			h2('The Radio Card variant'),
			p(
				'If you’re building a pricing-tier picker, a plan selector, or any UI where each option needs an icon and a description rather than a bare label, Marmo’s ',
				{ t: 'Radio Card component', href: '/docs/components/radio-card' },
				' ships that pattern directly. In MUI you’d build it from Radio + Card + manual ARIA wiring — doable, but it’s exactly the kind of component an AI agent tends to get subtly wrong (missing role, missing keyboard handling) when assembling it from primitives rather than using a purpose-built one.',
			),
			p(
				'Full props on the ',
				{ t: 'Radio Group docs page', href: '/docs/components/radio-group' },
				' and the ',
				{ t: 'Radio Card docs page', href: '/docs/components/radio-card' },
				'.',
			),
		],
	},
	{
		id: 'article-skeleton-marmo-vs-mui',
		slug: 'skeleton-loading-marmo-ui-vs-mui',
		title: 'Skeleton Loading: Marmo UI vs MUI',
		excerpt:
			'How Marmo UI’s Skeleton component compares to MUI’s — shape variants, animation, and matching skeleton dimensions to real content so loading states don’t jump on resolve.',
		seoTitle: 'Skeleton Component: Marmo UI vs MUI Loading States (2026)',
		seoDescription:
			'Marmo UI vs MUI Skeleton component: shape variants, animation defaults, and how to size skeletons to avoid layout shift when content loads.',
		body: [
			p(
				'A skeleton loader is a small component with one job: hint at the shape of content that is about to appear, without causing layout shift when it does. Here is how ',
				{ t: 'Marmo UI’s Skeleton', href: '/docs/components/skeleton' },
				" compares to MUI's.",
			),
			h2('Shape variants'),
			p(
				'MUI ships three variants — text, circular, and rectangular — with width/height set via sx or inline style, and a wave or pulse animation option.',
			),
			p(
				"Marmo UI's Skeleton uses the same core shape set (text/circular/rectangular) plus token-based sizing (matching the same size scale used across other components), so a skeleton for a component and the component's own default size stay in sync by construction rather than by manually copying pixel values between the two.",
			),
			h2('Avoiding layout shift'),
			...bullets([
				['The most common skeleton bug in either library is a skeleton sized differently from the real content it precedes — the page jumps the instant data loads.'],
				['MUI: width/height are freeform, so keeping them in sync with the eventual real content is a manual discipline.'],
				['Marmo UI: because component sizing follows the same token scale everywhere, a skeleton built with size="md" matches a real component built with size="md" without hand-tuning pixel values.'],
			]),
			h2('Composing skeleton states for a whole page'),
			p(
				"For a dashboard with multiple cards, tables, and charts loading independently, you typically want a skeleton version of each real component, not one generic gray box. This is where Marmo's MCP-connected workflow differs most from copy-pasting MUI examples: an agent with access to Marmo's component APIs can generate a matching skeleton state alongside the real component in the same pass, using the same size tokens, instead of you writing loading-state markup by hand afterward.",
			),
			p(
				'Full props and examples on the ',
				{ t: 'Skeleton docs page', href: '/docs/components/skeleton' },
				'.',
			),
		],
	},
];

async function main() {
	for (const a of articles) {
		await client.createOrReplace({
			_id: a.id,
			_type: 'article',
			title: a.title,
			slug: { _type: 'slug', current: a.slug },
			excerpt: a.excerpt,
			publishedAt: new Date().toISOString(),
			body: a.body,
			seoTitle: a.seoTitle,
			seoDescription: a.seoDescription,
		});
		console.log(`✅ ${a.title} -> /blog/${a.slug}`);
	}
}

main().catch(e => {
	console.error(e);
	process.exit(1);
});
