import type { Metadata } from 'next';
import Link from 'next/link';
import { MdCheck, MdClose } from 'react-icons/md';
import siteConfig from '@/../site.config';
import { BuyProButton } from '@/components/buy-pro-button';

export const metadata: Metadata = {
	title: `Pricing — ${siteConfig.title}`,
	description:
		'The components and the Core MCP are free forever. Pro unlocks on-brand generation, patterns, and Pro blocks for your AI agent.',
};

const tiers = [
	{
		name: 'Free',
		tagline: 'Open-source components + Core MCP',
		price: '$0',
		priceNote: 'forever',
		cta: { label: 'Start building', href: siteConfig.docsUrl, primary: false },
		features: [
			'Every core component — MIT licensed',
			'Free Core MCP: connect Claude Code, Codex, Cursor, Gemini CLI',
			'Free account: personal MCP token, no rate limits, saved DESIGN.md',
			'Live component APIs — your agent never guesses props',
			'Generated code validated before it lands',
			'Component docs, Storybook, Figma library',
			'Light + dark mode from the same tokens',
			'Unlimited projects, commercial use',
		],
	},
	{
		name: 'Pro',
		tagline: 'Your brand, generated by any agent',
		price: '$9.99',
		priceNote: 'per month · 14-day free trial',
		cta: { label: 'Start free trial', href: siteConfig.buyNowUrl, primary: true },
		features: [
			'Everything in Free',
			'On-brand generation: feed the MCP your DESIGN.md, every screen comes out in your style',
			'Composition patterns — app shells, settings pages, dashboards',
			'Pro blocks, generated straight into your repo',
			'Personal MCP token + dashboard',
			'Hosted design-system site at marmoui.com/t/your-team — the library in your tokens',
			'Pattern & Pro-component docs',
			'Priority support',
		],
	},
];

const comparison: { label: string; free: boolean; pro: boolean }[] = [
	{ label: 'React components (@marmoui/ui, MIT)', free: true, pro: true },
	{ label: 'Core MCP — live props & generation rules', free: true, pro: true },
	{ label: 'Personal token + saved DESIGN.md (free account)', free: true, pro: true },
	{ label: 'Generated-code validation', free: true, pro: true },
	{ label: 'Docs, Storybook, Figma library', free: true, pro: true },
	{ label: 'On-brand generation from your DESIGN.md', free: false, pro: true },
	{ label: 'Composition patterns library', free: false, pro: true },
	{ label: 'Pro blocks', free: false, pro: true },
	{ label: 'Personal MCP token', free: false, pro: true },
	{ label: 'Hosted design-system site (/t/your-team)', free: false, pro: true },
];

const pricingFaq = [
	{
		q: 'What exactly do I pay for?',
		a: 'The MCP knowledge tier. Components stay free and open source; Pro unlocks on-brand generation (your tokens, your DESIGN.md), the patterns library, and Pro blocks that your agent generates directly into your repo.',
	},
	{
		q: 'Is it a subscription?',
		a: 'Yes — Pro is $9.99 per month with a 14-day free trial, billed through Lemon Squeezy. Cancel anytime; you keep Free forever.',
	},
	{
		q: 'Who owns the generated code?',
		a: 'You do, entirely. Your agent generates it with your own LLM tokens, and it lives in your repository. Nothing phones home.',
	},
	{
		q: 'Does the free tier really include the MCP?',
		a: 'Yes. The Core MCP tier — public component knowledge with the default Marmo styling — is free and needs no account. Pro adds your brand on top.',
	},
];

export default function PricingPage() {
	return (
		<div className="bg-bg">
			<div className="mx-auto max-w-7xl px-4 py-20 md:px-6 md:py-28">
				{/* Head */}
				<div className="mx-auto max-w-2xl text-center">
					<p className="mb-3 font-['Plus_Jakarta_Sans',sans-serif] text-[18px] font-semibold text-primary tracking-[-0.36px]">
						Pricing
					</p>
					<h1 className="font-['Plus_Jakarta_Sans',sans-serif] text-[44px] font-bold text-ink-dark tracking-[-1.3px] leading-[1.1] md:text-[52px]">
						Free to build. Pro to brand.
					</h1>
					<p className="mt-5 text-[18px] leading-[1.5] text-ink-light">
						The components and the Core MCP are free, forever — that is the point. Pro is for teams
						that want every agent-generated screen in their own style.
					</p>
				</div>

				{/* Tier cards */}
				<div className="mx-auto mt-14 grid max-w-4xl gap-6 md:grid-cols-2">
					{tiers.map(tier => (
						<div key={tier.name} className="rounded-[16px] border border-[#f1e4f2] bg-white p-4">
							<div className="flex h-full flex-col gap-5 rounded-[8px] border border-[#e6d5e7] bg-white p-6 shadow-[0_1px_1.5px_rgba(0,0,0,0.05)]">
								<div className="flex flex-col gap-1">
									<h2 className="font-['Plus_Jakarta_Sans',sans-serif] text-[28px] font-semibold text-ink-dark tracking-[-0.84px]">
										{tier.name}
									</h2>
									<p className="text-[15px] text-ink-light">{tier.tagline}</p>
								</div>
								<p className="font-['Plus_Jakarta_Sans',sans-serif] text-[40px] font-semibold text-ink-dark tracking-[-1.2px]">
									{tier.price}
									<span className="ml-2 align-middle text-[14px] font-medium text-ink-light">
										{tier.priceNote}
									</span>
								</p>
								{tier.cta.primary ? (
									<BuyProButton className="h-12 w-full text-[16px] font-medium">
										{tier.cta.label}
									</BuyProButton>
								) : (
									<Link
										href={tier.cta.href}
										className="inline-flex h-12 w-full items-center justify-center rounded-[6px] border border-border-secondary bg-white text-[16px] font-medium text-ink transition-colors hover:bg-panel"
									>
										{tier.cta.label}
									</Link>
								)}
								<ul className="space-y-2.5">
									{tier.features.map(f => (
										<li key={f} className="flex items-start gap-2.5 text-[14px] leading-[1.45] text-ink-dark">
											<MdCheck className="mt-0.5 size-4 shrink-0 text-primary" aria-hidden />
											{f}
										</li>
									))}
								</ul>
							</div>
						</div>
					))}
				</div>

				{/* Comparison table */}
				<div className="mx-auto mt-20 max-w-3xl">
					<h2 className="mb-6 text-center font-['Plus_Jakarta_Sans',sans-serif] text-[28px] font-bold text-ink-dark tracking-[-0.84px]">
						What&apos;s in each tier
					</h2>
					<div className="overflow-x-auto rounded-[12px] border border-border-secondary bg-white">
						<table className="w-full min-w-[480px] text-left text-[14px]">
							<thead>
								<tr className="border-b border-border-secondary bg-panel text-[12px] font-semibold uppercase tracking-[0.04em] text-ink">
									<th className="px-5 py-3 font-semibold">Capability</th>
									<th className="w-24 px-3 py-3 text-center font-semibold">Free</th>
									<th className="w-24 px-3 py-3 text-center font-semibold">Pro</th>
								</tr>
							</thead>
							<tbody>
								{comparison.map(row => (
									<tr key={row.label} className="border-b border-border-secondary last:border-0">
										<td className="px-5 py-3 text-ink-dark">{row.label}</td>
										<td className="px-3 py-3 text-center">
											{row.free ? (
												<MdCheck className="mx-auto size-4 text-primary" aria-label="Included" />
											) : (
												<MdClose className="mx-auto size-4 text-ink-muted" aria-label="Not included" />
											)}
										</td>
										<td className="px-3 py-3 text-center">
											{row.pro ? (
												<MdCheck className="mx-auto size-4 text-primary" aria-label="Included" />
											) : (
												<MdClose className="mx-auto size-4 text-ink-muted" aria-label="Not included" />
											)}
										</td>
									</tr>
								))}
							</tbody>
						</table>
					</div>
				</div>

				{/* FAQ */}
				<div className="mx-auto mt-20 max-w-2xl">
					<h2 className="mb-8 text-center font-['Plus_Jakarta_Sans',sans-serif] text-[28px] font-bold text-ink-dark tracking-[-0.84px]">
						Pricing questions
					</h2>
					<dl className="space-y-8">
						{pricingFaq.map(item => (
							<div key={item.q}>
								<dt className="font-['Plus_Jakarta_Sans',sans-serif] text-[17px] font-semibold text-ink-dark">
									{item.q}
								</dt>
								<dd className="mt-2 text-[15px] leading-relaxed text-ink-light">{item.a}</dd>
							</div>
						))}
					</dl>
				</div>

				{/* Bottom CTA */}
				<div className="mx-auto mt-20 max-w-2xl rounded-[12px] border border-border-secondary bg-panel px-8 py-10 text-center">
					<h2 className="font-['Plus_Jakarta_Sans',sans-serif] text-[24px] font-bold text-ink-dark tracking-[-0.72px]">
						Try it free first
					</h2>
					<p className="mx-auto mt-2 max-w-md text-[15px] leading-relaxed text-ink-light">
						Connect your agent to the free Core MCP and generate a screen. Upgrade when you want it
						in your brand.
					</p>
					<div className="mt-6 flex flex-wrap items-center justify-center gap-3">
						<Link
							href={siteConfig.connectUrl}
							className="inline-flex h-11 items-center rounded-[6px] bg-[#141422] px-6 text-[15px] font-semibold text-white transition-opacity hover:opacity-90"
						>
							Connect your agent
						</Link>
						<Link
							href={siteConfig.docsUrl}
							className="inline-flex h-11 items-center rounded-[6px] border border-border-secondary bg-white px-5 text-[15px] font-medium text-ink transition-colors hover:bg-panel"
						>
							Read the docs
						</Link>
					</div>
				</div>
			</div>
		</div>
	);
}
